docker:
  image: yegor256/rultor-image:1.3
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
architect:
  - vzurauskas
readers:
  - "urn:github:18754033"
assets:
  settings.xml: vzurauskas/secrets#nereides/settings.xml
  pubring.gpg: vzurauskas/secrets#pubring.gpg
  secring.gpg: vzurauskas/secrets#secring.gpg
merge:
  script: |
    mvn clean install -Pwall --errors
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pwall -Pnereides -Prelease --errors --settings /home/r/settings.xml
